apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  annotations:
    metallb.universe.tf/allow-shared-ip: "true"
spec:
  type: LoadBalancer
  ports:
  - name: phpmyadmin
    port: 5000
    targetPort: 5000
    protocol: TCP
  selector:
    app: phpmyadmin
# LoadBalancer part - to define acces to a pod
# How pod se connecte avec minikube
---
# Define the deployment, how many instances to use, do we have to refresh
# Pod lui meme
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin
        ports:
        - containerPort: 5000
          name: phpmyadmin
        imagePullPolicy: IfNotPresent
